#!/usr/bin/env python3
"""
CI/CD Pipeline Generator for Counterscarp Engine.

Generates platform-specific CI/CD pipeline configurations based on counterscarp.toml
settings. Supports GitHub Actions, GitLab CI, Azure DevOps, and Jenkins.

Example:
    >>> from pipeline_generator import generate_pipeline
    >>> yaml_content = generate_pipeline("counterscarp.toml", "github")
    >>> print(yaml_content)

CLI Usage:
    $ counterscarp-generate-pipeline --platform github --config counterscarp.toml
    $ python pipeline_generator.py --platform gitlab --output .gitlab-ci.yml
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Callable, Dict, List, Optional, Any, TYPE_CHECKING
from pathlib import Path

if TYPE_CHECKING:
    from config_loader import CounterscarpConfig

# Import logger and exceptions
try:
    from logger import get_logger
    from exceptions import (
        CounterscarpConfigError,
        CounterscarpValidationError,
        CounterscarpError,
    )
    LOGGER_AVAILABLE = True
except ImportError:
    LOGGER_AVAILABLE = False
    get_logger: Optional[Callable[..., Any]] = None  # type: ignore[no-redef]
    CounterscarpConfigError = Exception  # type: ignore[misc,assignment]
    CounterscarpValidationError = ValueError  # type: ignore[misc,assignment]
    CounterscarpError = Exception  # type: ignore[misc,assignment]

# Initialize logger
if LOGGER_AVAILABLE and get_logger is not None:
    logger = get_logger(__name__)
else:
    import logging
    logger = logging.getLogger(__name__)

# Try to import config loader
try:
    from config_loader import load_config
    CONFIG_LOADER_AVAILABLE = True
except ImportError:
    CONFIG_LOADER_AVAILABLE = False
    load_config: Optional[Any] = None  # type: ignore[no-redef]


# =============================================================================
# Template Constants
# =============================================================================

# GitHub Actions Template
GITHUB_ACTIONS_TEMPLATE = '''name: Counterscarp Security Audit

on:
{triggers}

permissions:
  contents: read
  pull-requests: write
  security-events: write

env:
  COUNTERSCARP_FAIL_ON_SEVERITY: "{fail_on_severity}"
  COUNTERSCARP_REPORT_FORMAT: "{report_format}"

jobs:
  counterscarp-security-scan:
    runs-on: ubuntu-latest
    name: Counterscarp Security Analysis
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Counterscarp Engine dependencies
        run: |
          pip install slither-analyzer requests packaging tomli
          pip install solc-select
          solc-select install 0.8.19
          solc-select use 0.8.19
      
      - name: Run Counterscarp Engine Scan
        id: counterscarp_scan
        run: |
          python -m counterscarp-engine --target {target_path} --config {config_path} --report > counterscarp_output.txt 2>&1 || true
          cat counterscarp_output.txt
      
{analyzer_steps}
      
      - name: Generate SARIF Report
        run: |
          python -c "
import sys
sys.path.insert(0, '.')
try:
    from report_generator import save_sarif_report
    save_sarif_report([], 'counterscarp-report.sarif', {{'project_name': 'counterscarp-scan'}})
    print('SARIF report generated')
except Exception as e:
    print(f'SARIF generation skipped: {{e}}')
"
      
      - name: Upload SARIF to GitHub Security Tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: counterscarp-report.sarif
          category: counterscarp-engine
      
      - name: Check for Critical/High Issues
        id: check_severity
        run: |
          CRITICAL=$(grep -c '\\[CRITICAL\\]' counterscarp_output.txt || echo 0)
          HIGH=$(grep -c '\\[HIGH\\]' counterscarp_output.txt || echo 0)
          echo "critical_count=$CRITICAL" >> $GITHUB_OUTPUT
          echo "high_count=$HIGH" >> $GITHUB_OUTPUT
          
          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            echo "::error::Found $CRITICAL critical and $HIGH high severity issues"
            exit 1
          fi
      
      - name: Upload Scan Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: counterscarp-security-report
          path: |
            counterscarp_output.txt
            counterscarp-report.sarif
            ACTION_PLAN_*.md
            audit_report_*.html
{notification_steps}
'''

# GitLab CI Template
GITLAB_CI_TEMPLATE = '''# Counterscarp Security Engine - GitLab CI Pipeline
# Generated by Counterscarp Pipeline Generator

stages:
  - security

variables:
  COUNTERSCARP_FAIL_ON_SEVERITY: "{fail_on_severity}"
  COUNTERSCARP_REPORT_FORMAT: "{report_format}"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - solc-versions/

counterscarp-security-scan:
  stage: security
  image: python:3.10-slim
  
  before_script:
    - apt-get update && apt-get install -y git gcc
    - pip install slither-analyzer requests packaging tomli
    - pip install solc-select
    - solc-select install 0.8.19
    - solc-select use 0.8.19
  
  script:
    - echo "Running Counterscarp Security Scan..."
    - python -m counterscarp-engine --target {target_path} --config {config_path} --report || true
    - |
      CRITICAL=$(grep -c '\\[CRITICAL\\]' counterscarp_output.txt 2>/dev/null || echo 0)
      HIGH=$(grep -c '\\[HIGH\\]' counterscarp_output.txt 2>/dev/null || echo 0)
      echo "Found $CRITICAL critical and $HIGH high severity issues"
      
      if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
        echo "Security scan failed - critical/high issues found"
        exit 1
      fi
  
{analyzer_steps}
  
  artifacts:
    when: always
    paths:
      - counterscarp_output.txt
      - ACTION_PLAN_*.md
      - audit_report_*.html
    expire_in: 30 days
  
  rules:
{trigger_rules}
{notification_steps}
'''

# Azure DevOps Template
AZURE_DEVOPS_TEMPLATE = '''# Counterscarp Security Engine - Azure DevOps Pipeline
# Generated by Counterscarp Pipeline Generator

trigger:
{triggers}

pool:
  vmImage: 'ubuntu-latest'

variables:
  COUNTERSCARP_FAIL_ON_SEVERITY: '{fail_on_severity}'
  COUNTERSCARP_REPORT_FORMAT: '{report_format}'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Set up Python'

- script: |
    pip install slither-analyzer requests packaging tomli
    pip install solc-select
    solc-select install 0.8.19
    solc-select use 0.8.19
  displayName: 'Install Counterscarp Dependencies'

- script: |
    python -m counterscarp-engine --target {target_path} --config {config_path} --report > counterscarp_output.txt 2>&1 || true
    cat counterscarp_output.txt
  displayName: 'Run Counterscarp Security Scan'

{analyzer_steps}

- script: |
    CRITICAL=$(grep -c '\\[CRITICAL\\]' counterscarp_output.txt || echo 0)
    HIGH=$(grep -c '\\[HIGH\\]' counterscarp_output.txt || echo 0)
    echo "Found $CRITICAL critical and $HIGH high severity issues"
    
    if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
      echo "##vso[task.logissue type=error]Security scan failed - critical/high issues found"
      exit 1
    fi
  displayName: 'Check Severity Thresholds'
  failOnStderr: false

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)'
    artifactName: 'counterscarp-reports'
    publishLocation: 'Container'
  condition: always()
{notification_steps}
'''

# Jenkinsfile Template
JENKINSFILE_TEMPLATE = '''// Counterscarp Security Engine - Jenkins Pipeline
// Generated by Counterscarp Pipeline Generator

pipeline {{
    agent any
    
    environment {{
        COUNTERSCARP_FAIL_ON_SEVERITY = '{fail_on_severity}'
        COUNTERSCARP_REPORT_FORMAT = '{report_format}'
    }}
    
    options {{
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timestamps()
    }}
    
    stages {{
        stage('Setup') {{
            steps {{
                sh """
                    pip install slither-analyzer requests packaging tomli
                    pip install solc-select
                    solc-select install 0.8.19 || true
                    solc-select use 0.8.19 || true
                """
            }}
        }}
        
        stage('Security Scan') {{
            steps {{
                sh """
                    python -m counterscarp-engine --target {target_path} --config {config_path} --report > counterscarp_output.txt 2>&1 || true
                    cat counterscarp_output.txt
                """
            }}
        }}
        
{analyzer_stages}
        
        stage('Check Thresholds') {{
            steps {{
                script {{
                    def critical = sh(
                        script: "grep -c '\\\\[CRITICAL\\\\]' counterscarp_output.txt || echo 0",
                        returnStdout: true
                    ).trim()
                    def high = sh(
                        script: "grep -c '\\\\[HIGH\\\\]' counterscarp_output.txt || echo 0",
                        returnStdout: true
                    ).trim()
                    
                    echo "Found ${{critical}} critical and ${{high}} high severity issues"
                                        
                    if (${{critical}}.toInteger() > 0 || ${{high}}.toInteger() > 0) {{
                        error("Security scan failed - critical/high issues found")
                    }}
                }}
            }}
        }}
    }}
    
    post {{
        always {{
            archiveArtifacts artifacts: 'counterscarp_output.txt, ACTION_PLAN_*.md, audit_report_*.html', allowEmptyArchive: true
        }}
{notification_post}
    }}
}}
'''

# Docker-based execution template (can be embedded in any platform)
DOCKER_EXECUTION_TEMPLATE = '''
      - name: Run Counterscarp via Docker
        run: |
          docker run --rm \\
            -v $(pwd):/workspace \\
            -w /workspace \\
            counterscarp-engine:latest \\
            --target {target_path} --config {config_path} --report
'''

# Analyzer step templates
SLITHER_STEP = '''      - name: Run Slither Analysis
        run: |
          slither {target_path} --filter-paths "test|script|node_modules" --config-file {config_path} || true
'''

ADERYN_STEP = '''      - name: Run Aderyn Analysis
        run: |
          if command -v aderyn &> /dev/null; then
            aderyn {target_path} || true
          else
            echo "Aderyn not installed, skipping"
          fi
'''

MEDUSA_STEP = '''      - name: Run Medusa Fuzzing
        run: |
          if command -v medusa &> /dev/null; then
            medusa fuzz --target {target_path} || true
          else
            echo "Medusa not installed, skipping"
          fi
'''

HEURISTICS_STEP = '''      - name: Run Heuristic Scan
        run: |
          python heuristic_scanner.py {target_path} --config {config_path} || true
'''

# Notification templates
SLACK_NOTIFICATION_STEP = '''
      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {{
              "text": "Counterscarp Security Scan ${{ job.status }}",
              "blocks": [
                {{
                  "type": "section",
                  "text": {{
                    "type": "mrkdwn",
                    "text": "*Counterscarp Security Scan*\\nStatus: ${{ job.status }}"
                  }}
                }}
              ]
            }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
'''

DISCORD_NOTIFICATION_STEP = '''
      - name: Notify Discord
        if: always()
        uses: Ilshidur/action-discord@master
        with:
          args: "Counterscarp Security Scan ${{ job.status }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
'''


# =============================================================================
# Core Functions
# =============================================================================

def _get_triggers(config: Optional[CounterscarpConfig], platform: str) -> str:
    """Generate trigger configuration for the specified platform.
    
    Args:
        config: Counterscarp configuration object.
        platform: CI/CD platform (github, gitlab, azure, jenkins).
    
    Returns:
        Platform-specific trigger configuration string.
    """
    # Default triggers
    default_triggers = ["push", "pull_request"]
    
    # Get triggers from config if available
    triggers = default_triggers
    if config and hasattr(config, 'ci') and config.ci and config.ci.generator:
        if hasattr(config.ci.generator, 'triggers') and config.ci.generator.triggers:
            triggers = config.ci.generator.triggers
    
    if platform == "github":
        trigger_lines = []
        if "push" in triggers:
            trigger_lines.append("  push:")
            trigger_lines.append("    branches: [ main, develop ]")
        if "pull_request" in triggers:
            trigger_lines.append("  pull_request:")
            trigger_lines.append("    branches: [ main, develop ]")
        if "schedule" in triggers:
            trigger_lines.append("  schedule:")
            trigger_lines.append("    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM")
        if "workflow_dispatch" in triggers or not trigger_lines:
            trigger_lines.append("  workflow_dispatch:")
        return "\n".join(trigger_lines)
    
    elif platform == "gitlab":
        # GitLab uses rules instead of triggers in the template
        rules = []
        if "push" in triggers:
            rules.append("    - if: '$CI_COMMIT_BRANCH == \"main\"'")
            rules.append("    - if: '$CI_COMMIT_BRANCH == \"develop\"'")
        if "pull_request" in triggers:
            rules.append("    - if: '$CI_MERGE_REQUEST_ID'")
        if "schedule" in triggers:
            rules.append("    - if: '$CI_PIPELINE_SOURCE == \"schedule\"\"'")
        if not rules:
            rules.append("    - when: always")
        return "\n".join(rules)
    
    elif platform == "azure":
        # Azure uses branch filters
        branch_list = ["main", "develop"]
        return "\n".join([f"  - {branch}" for branch in branch_list])
    
    elif platform == "jenkins":
        # Jenkins triggers are configured differently
        return ""  # Handled in pipeline options
    
    return ""


def _get_analyzer_steps(config: Optional[CounterscarpConfig], platform: str, target_path: str, config_path: str) -> str:
    """Generate analyzer execution steps based on configuration.
    
    Args:
        config: Counterscarp configuration object.
        platform: CI/CD platform.
        target_path: Path to target contracts.
        config_path: Path to counterscarp config file.
    
    Returns:
        Platform-specific analyzer steps string.
    """
    steps = []
    
    # Determine which analyzers are enabled
    slither_enabled = True
    aderyn_enabled = False
    medusa_enabled = False
    heuristics_enabled = True
    
    if config:
        if hasattr(config, 'static_analysis'):
            slither_enabled = getattr(config.static_analysis, 'slither_enabled', True)
            aderyn_enabled = getattr(config.static_analysis, 'aderyn_enabled', False)
        if hasattr(config, 'fuzzing'):
            medusa_enabled = getattr(config.fuzzing, 'medusa_enabled', False)
        if hasattr(config, 'heuristics'):
            heuristics_enabled = getattr(config.heuristics, 'enabled', True)
    
    if platform == "github":
        if slither_enabled:
            steps.append(SLITHER_STEP.format(target_path=target_path, config_path=config_path))
        if aderyn_enabled:
            steps.append(ADERYN_STEP.format(target_path=target_path, config_path=config_path))
        if medusa_enabled:
            steps.append(MEDUSA_STEP.format(target_path=target_path, config_path=config_path))
        if heuristics_enabled:
            steps.append(HEURISTICS_STEP.format(target_path=target_path, config_path=config_path))
    
    elif platform == "gitlab":
        # GitLab uses script blocks
        if slither_enabled:
            steps.append("    - slither {target_path} --filter-paths \"test|script|node_modules\" || true".format(
                target_path=target_path
            ))
        if heuristics_enabled:
            steps.append("    - python heuristic_scanner.py {target_path} --config {config_path} || true".format(
                target_path=target_path, config_path=config_path
            ))
    
    elif platform == "azure":
        # Azure uses script tasks
        if slither_enabled:
            steps.append("- script: |\n    slither {target_path} --filter-paths \"test|script|node_modules\" || true\n  displayName: 'Run Slither'".format(
                target_path=target_path
            ))
        if heuristics_enabled:
            steps.append("- script: |\n    python heuristic_scanner.py {target_path} --config {config_path} || true\n  displayName: 'Run Heuristics'".format(
                target_path=target_path, config_path=config_path
            ))
    
    elif platform == "jenkins":
        # Jenkins uses stages
        stage_template = '''        stage('{name}') {{
            steps {{
                script {{
                    sh '{command}'
                }}
            }}
        }}'''
        if slither_enabled:
            steps.append(stage_template.format(
                name="Slither Analysis",
                command=f"slither {target_path} --filter-paths \"test|script|node_modules\" || true"
            ))
        if heuristics_enabled:
            steps.append(stage_template.format(
                name="Heuristic Scan",
                command=f"python heuristic_scanner.py {target_path} --config {config_path} || true"
            ))
    
    return "\n".join(steps) if steps else ""


def _get_notification_steps(config: Optional[CounterscarpConfig], platform: str) -> str:
    """Generate notification steps based on configuration.
    
    Args:
        config: Counterscarp configuration object.
        platform: CI/CD platform.
    
    Returns:
        Platform-specific notification steps string.
    """
    notifications = []
    
    # Get notifications from config
    if config and hasattr(config, 'ci') and config.ci and config.ci.generator:
        if hasattr(config.ci.generator, 'notifications') and config.ci.generator.notifications:
            notifications = config.ci.generator.notifications
    
    if platform == "github":
        steps = []
        if "slack" in notifications:
            steps.append(SLACK_NOTIFICATION_STEP)
        if "discord" in notifications:
            steps.append(DISCORD_NOTIFICATION_STEP)
        return "\n".join(steps)
    
    elif platform == "gitlab":
        # GitLab uses notify blocks
        notify_blocks = []
        if "slack" in notifications:
            notify_blocks.append("  notify:\n    slack:\n      webhook: $SLACK_WEBHOOK_URL")
        return "\n".join(notify_blocks)
    
    elif platform == "azure":
        # Azure uses service hooks or REST API
        if "slack" in notifications:
            return "\n- task: CmdLine@2\n  inputs:\n    script: 'echo \"Slack notification would be sent here\"'\n  displayName: 'Notify Slack'"
        return ""
    
    elif platform == "jenkins":
        # Jenkins uses post block
        post_blocks = []
        if "slack" in notifications:
            post_blocks.append('''        success {
            slackSend(color: 'good', message: "Counterscarp Scan Passed: ${env.JOB_NAME} #${env.BUILD_NUMBER}")
        }}
        failure {{
            slackSend(color: 'danger', message: "Counterscarp Scan Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}")
        }''')
        if not post_blocks:
            post_blocks.append("        always {\n            echo 'Pipeline completed'\n        }")
        return "\n".join(post_blocks)
    
    return ""


def _get_analyzer_stages_jenkins(config: Optional[CounterscarpConfig], target_path: str, config_path: str) -> str:
    """Generate Jenkins-specific analyzer stages.
    
    Args:
        config: Counterscarp configuration object.
        target_path: Path to target contracts.
        config_path: Path to counterscarp config file.
    
    Returns:
        Jenkins stages string.
    """
    return _get_analyzer_steps(config, "jenkins", target_path, config_path)


def generate_pipeline(
    config_path: str,
    platform: str,
    output_path: Optional[str] = None,
    target_path: str = "./contracts",
) -> str:
    """Generate a CI/CD pipeline configuration for the specified platform.
    
    Reads the counterscarp.toml configuration to determine which analyzers are
    enabled, fail thresholds, and report formats. Generates a platform-specific
    CI/CD pipeline file.
    
    Args:
        config_path: Path to the counterscarp.toml configuration file.
        platform: CI/CD platform to generate for. One of: github, gitlab, azure, jenkins.
        output_path: Optional path to write the generated pipeline file.
        target_path: Path to the target contracts directory.
    
    Returns:
        The generated pipeline content as a string.
    
    Raises:
        CounterscarpValidationError: If the platform is not supported.
        CounterscarpConfigError: If the configuration file cannot be loaded.
    
    Example:
        >>> content = generate_pipeline("counterscarp.toml", "github")
        >>> print(content)
        'name: Counterscarp Security Audit\\n...'
    """
    # Validate platform
    supported_platforms = ["github", "gitlab", "azure", "jenkins"]
    if platform.lower() not in supported_platforms:
        raise CounterscarpValidationError(
            f"Unsupported platform: {platform}",
            details={"supported": supported_platforms, "provided": platform}
        )
    
    platform = platform.lower()
    
    # Load configuration
    config = None
    if CONFIG_LOADER_AVAILABLE and load_config is not None:
        try:
            config = load_config(config_path)
            logger.info(f"Loaded configuration from: {config_path}")
        except Exception as e:
            logger.warning(f"Could not load config from {config_path}: {e}")
            raise CounterscarpConfigError(
                "Failed to load configuration",
                details={"path": config_path, "error": str(e)}
            ) from e
    else:
        logger.warning("Config loader not available, using defaults")
    
    # Extract configuration values
    fail_on_severity = "HIGH"
    report_format = "markdown"
    
    if config:
        if hasattr(config, 'engine') and hasattr(config.engine, 'fail_on_severity'):
            fail_on_severity = config.engine.fail_on_severity
        if hasattr(config, 'reporting') and hasattr(config.reporting, 'format'):
            report_format = config.reporting.format
    
    # Generate platform-specific content
    triggers = _get_triggers(config, platform)
    analyzer_steps = _get_analyzer_steps(config, platform, target_path, config_path)
    notification_steps = _get_notification_steps(config, platform)
    
    # Select and populate template
    if platform == "github":
        content = GITHUB_ACTIONS_TEMPLATE.format(
            triggers=triggers,
            fail_on_severity=fail_on_severity,
            report_format=report_format,
            target_path=target_path,
            config_path=config_path,
            analyzer_steps=analyzer_steps,
            notification_steps=notification_steps,
        )
    
    elif platform == "gitlab":
        trigger_rules = triggers  # For GitLab, triggers are rules
        content = GITLAB_CI_TEMPLATE.format(
            fail_on_severity=fail_on_severity,
            report_format=report_format,
            target_path=target_path,
            config_path=config_path,
            analyzer_steps=analyzer_steps,
            trigger_rules=trigger_rules,
            notification_steps=notification_steps,
        )
    
    elif platform == "azure":
        content = AZURE_DEVOPS_TEMPLATE.format(
            triggers=triggers,
            fail_on_severity=fail_on_severity,
            report_format=report_format,
            target_path=target_path,
            config_path=config_path,
            analyzer_steps=analyzer_steps,
            notification_steps=notification_steps,
        )
    
    elif platform == "jenkins":
        analyzer_stages = _get_analyzer_stages_jenkins(config, target_path, config_path)
        notification_post = notification_steps
        content = JENKINSFILE_TEMPLATE.format(
            fail_on_severity=fail_on_severity,
            report_format=report_format,
            target_path=target_path,
            config_path=config_path,
            analyzer_stages=analyzer_stages,
            notification_post=notification_post,
        )
    
    else:
        raise CounterscarpValidationError(f"Unexpected platform: {platform}")
    
    # Write to file if output path provided
    if output_path:
        try:
            output_dir = os.path.dirname(output_path)
            if output_dir and not os.path.exists(output_dir):
                os.makedirs(output_dir, exist_ok=True)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)
            logger.info(f"Pipeline written to: {output_path}")
        except IOError as e:
            raise CounterscarpConfigError(
                "Failed to write pipeline file",
                details={"path": output_path, "error": str(e)}
            ) from e
    
    return content


def main() -> None:
    """Main entry point for the pipeline generator CLI.
    
    Parses command-line arguments and generates the requested pipeline.
    """
    parser = argparse.ArgumentParser(
        description="Generate CI/CD pipeline configurations for Counterscarp Engine",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --platform github --config counterscarp.toml --output .github/workflows/counterscarp.yml
  %(prog)s --platform gitlab --config counterscarp.toml --output .gitlab-ci.yml
  %(prog)s --platform azure --config counterscarp.toml --output azure-pipelines.yml
  %(prog)s --platform jenkins --config counterscarp.toml --output Jenkinsfile
        """
    )
    
    parser.add_argument(
        "--platform",
        required=True,
        choices=["github", "gitlab", "azure", "jenkins"],
        help="CI/CD platform to generate pipeline for"
    )
    parser.add_argument(
        "--config",
        default="counterscarp.toml",
        help="Path to counterscarp.toml configuration file (default: counterscarp.toml)"
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output file path (default: print to stdout)"
    )
    parser.add_argument(
        "--target",
        default="./contracts",
        help="Path to target contracts directory (default: ./contracts)"
    )
    
    args = parser.parse_args()
    
    try:
        content = generate_pipeline(
            config_path=args.config,
            platform=args.platform,
            output_path=args.output,
            target_path=args.target,
        )
        
        if not args.output:
            print(content)
        else:
            print(f"✅ Generated {args.platform} pipeline: {args.output}")
            
    except CounterscarpValidationError as e:
        logger.error(f"Validation error: {e}")
        print(f"❌ Error: {e}", file=sys.stderr)
        sys.exit(1)
    except CounterscarpConfigError as e:
        logger.error(f"Configuration error: {e}")
        print(f"❌ Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        print(f"❌ Unexpected error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
